---
title: "Table 1"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(tabulizer)
library(here)
library(flextable)
library(officer)
library(lubridate)


```

```{r}

banding <- read.csv("C:/Users/scott.jennings/Documents/Projects/hetp/hetp_data_work/banding/HETP_banding.csv")%>% 
  mutate(parent.location = case_when(grepl("TOPO", location.code) ~ "TP",
                                     grepl("WACR", location.code) ~ "WC",
                                     grepl("CGRC", location.code) ~ "CG")) %>% 
  select(bird = Bird.ID, parent.location) %>% 
  drop_na()

bird_days <- readRDS(here("derived_data/amt_bursts/greg_steps_habitat")) %>% 
  data.frame() %>%  
  mutate(date = as.Date(t1_)) %>% 
  group_by(bird) %>% 
  distinct(date) %>% 
  summarise(n.days = n(),
            day.range = paste(as.character(min(date)), as.character(max(date)), sep = " to\n"))

total_steps_habitat <- readRDS(here("derived_data/amt_bursts/greg_steps_habitat")) %>% 
  data.frame() %>% 
  filter(case_ == TRUE) %>% 
  group_by(bird, wetland.end) %>% 
  summarise(num.steps = n()) %>%
  ungroup() %>% 
  pivot_wider(names_from = "wetland.end", values_from = "num.steps") %>% 
 mutate(across(everything(), ~replace_na(.x, 0))) %>% 
  mutate(tot.points = other.tidal + eelgrass + shellfish + tidal.marsh)


out_table <- full_join(bird_days, total_steps_habitat) %>% 
  filter(bird != "GREG_4") %>% 
  left_join(., banding) %>% 
  mutate(bird = ifelse(shellfish < 10, paste(bird, "*", sep = ""), bird),
         filler.col = "") %>% 
  dplyr::select(bird, parent.location, n.days, day.range, filler.col, eelgrass, shellfish, tidal.marsh, other.tidal, tot.points) %>% 
  arrange(-tot.points)

flextable(out_table) %>%   
  add_header_row(values = c("", "", "days tracked on Tomales Bay", "", "number of steps"), colwidths = c(1, 1, 2, 1, 5)) %>% 
  set_header_labels(bird = "Bird ID") %>%
  set_header_labels(parent.location = "capture site") %>%
  set_header_labels(n.days = "total days") %>%
  set_header_labels(day.range = "date range") %>%
  set_header_labels(filler.col = "") %>%
  set_header_labels(eelgrass = "eelgrass") %>% 
  set_header_labels(shellfish = "shellfish") %>% 
  set_header_labels(tidal.marsh = "tidal marsh") %>% 
  set_header_labels(other.tidal = "other tidal") %>% 
  set_header_labels(tot.points = "total steps") %>% 
  border_remove() %>% 
  border(i = 1, border.top = fp_border(color = "black"), part = "header") %>% 
  border(i = 1, j = 3:4, border.bottom = fp_border(color = "black"), part = "header") %>% 
  border(i = 1, j = 6:9, border.bottom = fp_border(color = "black"), part = "header") %>% 
  border(i = 1, border.top = fp_border(color = "black"), part = "body") %>% 
  border(i = nrow(out_table), border.bottom = fp_border(color = "black"), part = "body") %>% 
  align(j = 1, align = "left", part = "all") %>% 
  align(j = 2:10, align = "center", part = "all") %>% 
  valign(valign = "top", part = "all") %>% 
  fontsize(size = 10, part = "all") %>% 
  fit_to_width(max_width = 8.5) %>% 
  width(j = 1, width = 0.85) %>% 
  width(j = 2, width = 0.7) %>% 
  width(j = 3, width = 0.45) %>% 
  width(j = 4, width = 1.2) %>% 
  width(j = 5, width = 0.1) %>% 
  width(j = 6:7, width = 0.7)%>% 
  width(j = 8:10, width = 0.55)
```

